services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/darkrei08/nuxt-mcp-agent-starter:latest
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
